In [ ]:
#### Evaluación

In [1]:
### Cargar paqueterias 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
###cargar datos 
data=pd.read_csv('cuentas_credicel.csv',encoding='latin-1')

/var/folders/6c/rr21_80s11n3cvrghbnb5mz00000gn/T/ipykernel_48902/3674315777.py:2: DtypeWarning: Columns (26,31,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('cuentas_credicel.csv',encoding='latin-1')

In [4]:
data.head()

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,3,HDNAWQ3A,30,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,26.0,NaN
1,4,M418YNR4,33,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
2,5,SZ7V3NZT,37,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,74,NaN,NaN
3,6,9I08UIQZ,38,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
4,7,JMF4LKYU,44,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,0.0,0.0,0.0,NaN,NaN,74,NaN,NaN,NaN,NaN

In [5]:
###una copia de los datos
data2=data.copy()

In [7]:
###aplicar filtros 
##filtro 1 todo menos folio folio folio_solicitud, unamed33
filtro1 = data.drop(columns=['folio', 'folio_solicitud', 'Unnamed: 33',  'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36'])
filtro1.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
1,M418YNR4,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,225,1949.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
2,SZ7V3NZT,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,Cancelado,0.0,0.0,0.0,0,0.0,NaN
3,9I08UIQZ,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [8]:
###todas las filas multiplo de 4 
filtro2 = filtro1.iloc[::4, :]
filtro2.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
8,5SDZN7O1,14/11/2021 13:34,KODAK,LTE SEREN D60LX Azul,26S,2889.0,1000.0,0.0,131,1889.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0

In [11]:
###registros con la marca igual a ALCATEL, MOTOROLA, NOKIA, ZTE,SAMSUNG
filtro3 = filtro2[filtro2['marca'].isin(['ALCATEL', 'MOTOROLA', 'NOKIA', 'ZTE','SAMSUNG'])]
filtro3.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.0,625.0,0.0,130,1874.0,...,17/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [14]:
### registros entre 500 y 2000
filtro4 = filtro3[(filtro3['enganche'] >= 500) & (filtro3['enganche'] <= 2000)]
filtro4.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.0,625.0,0.0,130,1874.0,...,17/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [19]:
### todos los registros en la categoria en riesgo no sea cancelado o fraude 
filtro5 = filtro4[~filtro4['riesgo'].isin(['Cancelado', 'Fraude'])]
filtro5['riesgo'].value_counts()

riesgo
0        195
21.3      11
21.35     11
12.0      10
23.35      9
        ...
14.45      1
-5.55      1
12.85      1
5.7        1
-15.2      1
Name: count, Length: 1007, dtype: int64

In [21]:
filtro4['fecha'].value_counts()

fecha
12/11/2021 19:00    1
08/01/2023 12:54    1
09/01/2023 16:02    1
09/01/2023 15:36    1
09/01/2023 15:08    1
                   ..
01/10/2022 15:36    1
30/09/2022 18:29    1
30/09/2022 17:01    1
30/09/2022 12:40    1
18/04/2023 17:04    1
Name: count, Length: 2136, dtype: int64

In [26]:
###todos los registros cuya fecha sea posterior al 15/11/2021
filtro5 = filtro4[filtro4['fecha'] > '2021-11-15']

In [27]:
filtro5.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
28,74DZR6G2,23/11/2021 15:17,MOTOROLA,LTE XT2097-12 E7I POWER Naranja,26S,3299.0,990.0,0.0,160,2309.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
32,4VK0M9IK,26/11/2021 11:07,MOTOROLA,G10 B,39S,4299.0,1290.0,0.0,166,3009.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
36,HKHZDPMU,28/11/2021 12:35,NOKIA,1.4 2/32 AZUL B,26S,2599.0,650.0,0.0,135,1949.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
40,RYCSU33I,29/11/2021 16:52,MOTOROLA,MOTO G60 6+128 GB GRIS B,13S,7399.0,1850.0,0.0,640,5549.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
44,VNOHNLYD,30/11/2021 17:21,MOTOROLA,E7I POWER 2+32 GB ROJO B,52S,2999.0,750.0,0.0,112,2249.0,...,24/05/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,72

In [28]:
####convertir a csv
filtro5.to_csv('evaluacionpt1.csv', index=False)