In [ ]:
#### Evaluación

In [1]:
### Cargar paqueterias 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
###cargar datos 
data=pd.read_csv('cuentas_credicel.csv',encoding='latin-1')

/var/folders/6c/rr21_80s11n3cvrghbnb5mz00000gn/T/ipykernel_50021/3674315777.py:2: DtypeWarning: Columns (26,31,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('cuentas_credicel.csv',encoding='latin-1')

In [3]:
data.head()

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,3,HDNAWQ3A,30,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,26.0,NaN
1,4,M418YNR4,33,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
2,5,SZ7V3NZT,37,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,74,NaN,NaN
3,6,9I08UIQZ,38,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
4,7,JMF4LKYU,44,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,0.0,0.0,0.0,NaN,NaN,74,NaN,NaN,NaN,NaN

In [4]:
###una copia de los datos
data2=data.copy()

In [5]:
###aplicar filtros 
##filtro 1 todo menos folio folio folio_solicitud, unamed33
filtro1 = data.drop(columns=['folio', 'folio_solicitud', 'Unnamed: 33',  'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36'])
filtro1.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
1,M418YNR4,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,225,1949.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
2,SZ7V3NZT,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,Cancelado,0.0,0.0,0.0,0,0.0,NaN
3,9I08UIQZ,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [6]:
###todas las filas multiplo de 4 
filtro2 = filtro1.iloc[::4, :]
filtro2.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
8,5SDZN7O1,14/11/2021 13:34,KODAK,LTE SEREN D60LX Azul,26S,2889.0,1000.0,0.0,131,1889.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0

In [7]:
###registros con la marca igual a ALCATEL, MOTOROLA, NOKIA, ZTE,SAMSUNG
filtro3 = filtro2[filtro2['marca'].isin(['ALCATEL', 'MOTOROLA', 'NOKIA', 'ZTE','SAMSUNG'])]
filtro3.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.0,625.0,0.0,130,1874.0,...,17/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [8]:
### registros entre 500 y 2000
filtro4 = filtro3[(filtro3['enganche'] >= 500) & (filtro3['enganche'] <= 2000)]
filtro4.head()

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.0,1750.0,0.0,363,5249.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.0,2000.0,0.0,92,799.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.0,625.0,0.0,130,1874.0,...,17/03/2022 00:00,Mora,0.0,0,0.0,0.0,0.0,NaN,NaN,74

In [ ]:
### todos los registros en la categoria en riesgo no sea cancelado o fraude 
filtro5 = filtro4[~filtro4['riesgo'].isin(['Cancelado', 'Fraude'])]

riesgo
0        195
21.3      11
21.35     11
12.0      10
23.35      9
        ...
14.45      1
-5.55      1
12.85      1
5.7        1
-15.2      1
Name: count, Length: 1007, dtype: int64

In [10]:
pd.set_option("display.max_rows", None)
filtro5['riesgo'].value_counts()

riesgo
 0         195
 21.3       11
 21.35      11
 12.0       10
 23.35       9
 11.0        9
 18          8
 23.3        8
 23.5        7
 2           7
 17.3        7
 10.0        7
-16.7        6
 21.3        6
 32          6
 -29         6
 -8          6
 21.35       6
 4           6
 18.3        6
 8           6
 3           6
 -7          6
 -3          6
 1.35        5
 4.25        5
 27.35       5
 8.25        5
 9           5
 23.55       5
 17.55       5
 7.3         5
 19          5
 23.65       5
 15          5
 23.95       5
 7           5
 23.3        5
 17.85       4
 23.6        4
 24.75       4
 3.25        4
 26          4
 23.35       4
 30.5        4
 27.25       4
 6.3         4
 16.3        4
 21.55       4
 23.25       4
 14.5        4
 10.85       4
 -12.7       4
 1.3         4
 24.85       4
 15.6        4
 25          4
 11          4
 21          4
 9.0         4
 -17         4
 13          4
 -5          4
 13.0        4
 6           4
 -2          4
 26.25       3
 -12         3
 31.3        3
 33.5        3
 24.25       3
 17          3
 17.25       3
 23.7        3
 9.75        3
 -4.65       3
 22          3
 1.4         3
 22.35       3
 31.85       3
 33          3
 17.6        3
 -25         3
-8.65        3
 17.55       3
 27.1        3
 19.3        3
 1.55        3
 37.8        3
 10.5        3
 11.35       3
 29.3        3
 -20         3
 24.6        3
 23.75       3
 21.55       3
 11.3        3
 -0.15       3
 24.1        3
 17.3        3
 33.25       3
-7.25        3
 15.3        3
 -8.65       3
 24.5        3
 23.85       3
 27.85       3
 10          3
 -1          3
 11.5        3
 14.0        3
 21.5        3
 5           3
 -10.75      3
 31.45       3
 6.85        3
 26.55       2
 25.4        2
 -3.95       2
 -7.9        2
 11.6        2
 25.9        2
 -10.65      2
 34.4        2
 8.35        2
 2.85        2
 26.75       2
 10.2        2
 12.7        2
 5.3         2
 11.4        2
 23.8        2
 1.45        2
 7.15        2
 26.8        2
 3.65        2
 26.2        2
 6.4         2
 6.75        2
 14.2        2
 13.2        2
 24.05       2
 16.9        2
 32.05       2
 23.4        2
 22.9        2
 6.35        2
 -8.9        2
 28.5        2
 20.25       2
 18.35       2
 7.5         2
 -4.1        2
 5.5         2
 9.05        2
 -1.9        2
 28.55       2
 19.05       2
 7.85        2
 31.05       2
 32.95       2
 31.5        2
 -8.7        2
 13.75       2
 13.35       2
 17.5        2
 22.75       2
 22.65       2
 31.8        2
 -19.45      2
 16.5        2
 1.35        2
 23.15       2
 26.5        2
 25.3        2
 -4.15       2
 -16.6       2
 15.3        2
 10.3        2
 6.35        2
-15.65       2
 14.05       2
-9.25        2
 21.9        2
 21.6        2
 33.05       2
 27.3        2
 20.3        2
 10.6        2
 28.2        2
-4.25        2
 25.9        2
 8.05        2
 29.55       2
 7.55        2
 15.0        2
-10.65       2
 34.35       2
-14.55       2
 1.95        2
 23.1        2
 25.2        2
 16.9        2
 24.0        2
 25.4        2
 31.35       2
-8.8         2
 25.75       2
 30.8        2
 23.5        2
-6.9         2
 8.1         2
-2.65        2
 1.4         2
 10.05       2
 32.0        2
-8.1         2
 26.2        2
 14.25       2
 27.55       2
 24.3        2
 13.4        2
 5.0         2
 4.3         2
 19.65       2
 5.3         2
 27.65       2
 8.85        2
 16.95       2
 25.7        2
 -6.7        2
 24.2        2
 19.6        2
 22.35       2
 25.25       2
 25.55       2
 0.2         2
 7.75        2
 22.3        2
 7.35        2
 28.2        2
 2.45        2
-9.15        2
 26.75       2
 0.35        2
 17.5        2
 24.45       2
 20.0        2
 28.45       2
 25.1        2
 30.7        2
 35.2        2
 19.1        2
 20.85       2
 10.25       2
 0.3         2
 5.7         2
 6.4         2
 17.35       2
 20.2        2
 9.85        2
 22.45       2
 22.85       2
 23.9        2
 3.9         2
 8.0         2
 18.4        2
 -11.5       2
 3.3         2
 34.25       2
 10.35       2
 13.3        2
 1           2
 22.15       2
 7.3         2
 20.6        2
 -22         2
 27.3        2
 43.5        2
 27.75       2
 -21         2
 23          2
 8.15        2
 25.25       2
 -11         2
 11.25       2
 11.85       2
 29.9        2
 -14         2
 20          2
 19.85       2
 -24         2
 -10.25      2
 26.95       2
 24.95       2
 2.55        2
 19.9        2
 7.25        2
 -8.85       2
 9.1         2
 -0.7        2
 8.1         2
 -9.5        2
 25.5        2
 -4.95       2
 25.75       2
 -10         2
 4.05        2
 19.2        2
 17.8        2
 9.95        2
 2.3         2
 24.8        2
 5.4         2
 3.8         2
 17.7        2
 14.05       2
 -9          2
 21.15       2
 11.2        2
 -23         2
 27.5        2
 27          2
 -4.7        2
 14          2
 20.35       2
 -9.4        2
 9.7         2
 9.15        2
 -11.75      2
 34.15       2
 -3.2        2
 24.4        2
 -15.15      2
 0.4         2
 15.4        2
 30.35       2
 11.8        1
 21.1        1
 26.85       1
 -2.05       1
 8.3         1
-4.7         1
 29.3        1
-12.2        1
 16.55       1
 -19.1       1
 17.75       1
 29.8        1
 8.2         1
 27.95       1
 0.7         1
 26.3        1
 21.95       1
 27.8        1
 3.05        1
-17.55       1
 39.3        1
 23.05       1
 33.2        1
 21.8        1
-18.7        1
 21.5        1
 35.05       1
 11.2        1
 23.2        1
 8.35        1
 24.05       1
 29.45       1
 22.95       1
-8.35        1
-25.5        1
 30.1        1
 48.3        1
-17.95       1
-25.15       1
 -1.25       1
-24.05       1
-23.15       1
 13.25       1
-7.5         1
 33.35       1
 13.55       1
 19.85       1
 35.4        1
-17.3        1
 19.6        1
 -33         1
 14.3        1
-16.5        1
-16.15       1
 25.6        1
-7.0         1
 15.4        1
 -36.95      1
 -15.45      1
-10.3        1
 18.7        1
 41.25       1
-25.75       1
 9.55        1
 34.7        1
-6.65        1
 29.4        1
-24.15       1
 32.45       1
 37.05       1
 18.3        1
 22.7        1
 9.3         1
 35.65       1
 49.75       1
-25.7        1
 30.75       1
 31          1
-10.95       1
 22.65       1
 18.45       1
-4.45        1
-17.7        1
 21.4        1
 -0.55       1
 41.0        1
-9.7         1
-0.05        1
 -6.75       1
 2.95        1
 22.75       1
 26.05       1
 23.4        1
-12.5        1
 -5.15       1
 9.45        1
-1.85        1
-0.7         1
 11.15       1
 -27.9       1
 1.1         1
 -1.6        1
-12.7        1
 23.45       1
-13.15       1
 18.75       1
 2.45        1
 19.65       1
 18.55       1
 2.7         1
 -0.65       1
-4.95        1
-15.25       1
 2.05        1
 16.2        1
-9.55        1
 8.65        1
 18.65       1
 19.05       1
 8.5         1
 32.65       1
 0.2         1
 6.5         1
 -12.25      1
 13.3        1
-12.45       1
 22.15       1
 16.25       1
 14.85       1
 32.3        1
 16.75       1
 19.4        1
 31.6        1
 15.9        1
-5.1         1
 17.65       1
-4.75        1
 -0.45       1
-15.4        1
 14.25       1
-8.2         1
 20.65       1
 17.8        1
 22.3        1
 25.95       1
 34.1        1
 -1.1        1
-6.0         1
 7.9         1
 23.85       1
 7.5         1
 24.8        1
-13.6        1
 0.15        1
 12.15       1
 2.6         1
 -19         1
 -16         1
 -15         1
 36.1        1
 30.4        1
 0.6         1
 10.9        1
 7.85        1
 1.75        1
 31.15       1
 11.45       1
 4.9         1
-8.7         1
 24.6        1
 6.15        1
 29.15       1
-2.25        1
 17.75       1
-11.65       1
 27.25       1
 22.6        1
 24.9        1
 25.5        1
 45          1
 24.1        1
-7.9         1
-9.95        1
 19.55       1
-5.4         1
 62          1
 13.85       1
 35.15       1
 3.0         1
 6.25        1
-24.45       1
-16.45       1
 18.35       1
 28.4        1
 33.85       1
 16.5        1
-16.4        1
 19.15       1
 8.8         1
 5.4         1
 15.65       1
 2.5         1
 13.1        1
-5.6         1
 26.9        1
 16.85       1
 12          1
 32.55       1
 19.5        1
 -4          1
 11.65       1
-17.85       1
 15.2        1
-18.6        1
 5.45        1
 17.25       1
-8.45        1
 27.1        1
 16.4        1
 -26         1
 17.9        1
-6.15        1
 25.15       1
 9.1         1
-24.85       1
 24.5        1
 13.35       1
-10.9        1
 24.85       1
 23.2        1
 1.45        1
-1.4         1
 21.85       1
-25.6        1
 14.4        1
 46.4        1
 30.05       1
 15.35       1
 19.95       1
-12.65       1
 -31.9       1
 38.7        1
-23.9        1
 4.1         1
 27.6        1
-5.65        1
-2.6         1
 4.8         1
 -14.5       1
 35.75       1
 19.35       1
 32.6        1
 21.75       1
 5.85        1
 -6.5        1
 13.9        1
 27.0        1
-12.1        1
 25.05       1
 30.95       1
 3.8         1
 25.3        1
 1.55        1
 -8.4        1
-14.65       1
 -41.15      1
 19.8        1
 33.55       1
 9.5         1
 33.7        1
 29.05       1
 25.85       1
 1.3         1
 14.3        1
-2.1         1
 19.0        1
 27.75       1
 29          1
 24.7        1
 21.45       1
 25.35       1
 34.5        1
 26.0        1
 20.55       1
-8.75        1
-16.35       1
-3.0         1
-0.5         1
 32.8        1
 84          1
 -57         1
-6.6         1
 26.25       1
-18.4        1
 68          1
-23.0        1
 5.35        1
-7.65        1
 25.55       1
-8.6         1
 9.75        1
 32.1        1
 18.9        1
 1.6         1
 33.9        1
-19.4        1
 20.8        1
 38          1
 18.55       1
 24.75       1
 14.5        1
 12.9        1
-7.95        1
 22.2        1
 11.55       1
-14.15       1
-9.65        1
-0.15        1
-16.65       1
 59          1
 -9.85       1
 23.7        1
 35.55       1
 9.85        1
 -36         1
 -17.25      1
 -12.65      1
 41.5        1
 13.85       1
 -21.65      1
 39.5        1
 16.05       1
 15.6        1
 -17.1       1
 18.45       1
 16.35       1
 0.35        1
 5.6         1
 -2.65       1
 20.5        1
 38.5        1
 -22.85      1
 40.25       1
 -11.55      1
 0.5         1
 26.3        1
 9.25        1
 -8.1        1
 -8.2        1
 15.5        1
 27.6        1
 5.25        1
 27.05       1
 22.5        1
 -23.9       1
 -3.55       1
 6.45        1
 0.95        1
 28          1
 -23.85      1
 -16.65      1
 -11.35      1
 -3.45       1
 -14.85      1
 29.5        1
 -35.75      1
 -24.15      1
 29.35       1
 1.85        1
 8.55        1
 -9.65       1
 -7.65       1
 -2.75       1
 35.7        1
 17.85       1
 -2.7        1
 -8.3        1
 -27.8       1
 30.7        1
 7.95        1
 -6          1
 16.85       1
 -3.8        1
 -3.9        1
 0.7         1
 5.8         1
 17.45       1
 1.6         1
 24.25       1
 12.6        1
 -17.45      1
 11.65       1
 -35.9       1
 19.5        1
 30.15       1
 21.85       1
 19.75       1
 -23.2       1
 17.35       1
 22.45       1
 34.5        1
 32.25       1
 -2.85       1
 8.05        1
 -20.15      1
 26.1        1
 22.05       1
 21.8        1
 47.5        1
 -12.4       1
 25.1        1
 -17.95      1
 14.7        1
 -6.25       1
 14.65       1
 10.75       1
 -21.35      1
 24.9        1
 -14.7       1
 26.85       1
 -13.85      1
 7.05        1
 -36.05      1
 -7.1        1
 0.45        1
 12.35       1
 30.8        1
 13.05       1
 -20.85      1
 -21.3       1
 19.1        1
 -19.7       1
 12.95       1
 -20.95      1
 6.7         1
 28.65       1
 -10.8       1
 -3.75       1
 12.45       1
 -34.1       1
 53.2        1
 48.9        1
 18.15       1
 3.6         1
 21.2        1
 -5.6        1
 -15.3       1
 -25.6       1
 -0.35       1
 6.65        1
 -23.35      1
 0.3         1
 15.2        1
 8.65        1
 6.75        1
 21.1        1
 29.25       1
 39.05       1
 14.15       1
 -4.85       1
 0.85        1
 17.4        1
 -13.15      1
 27.9        1
 -3.3        1
 1.5         1
 7.9         1
 -9.6        1
 -23.95      1
 2.1         1
 3.55        1
 24          1
 23.1        1
 8.6         1
 -5.4        1
 -13.45      1
 28.6        1
 -14.3       1
 37          1
 16.25       1
 27.15       1
 -8.55       1
 -7.7        1
 23.45       1
 -10.7       1
 3.85        1
 30.65       1
 -26.5       1
 21.4        1
 0.65        1
 -6.1        1
 -1.7        1
 21.75       1
 8.5         1
 5.65        1
 30.2        1
 -4.55       1
 -12.6       1
 -9.15       1
 25.35       1
 -25.65      1
 -14.6       1
 -8.6        1
 14.9        1
 15.1        1
 3.15        1
 13.65       1
 21.7        1
 4.9         1
 39.15       1
 15.8        1
 5.35        1
 16.3        1
 24.45       1
 -4.25       1
 1.05        1
 25.05       1
 5.75        1
 41.65       1
 32.1        1
 31.85       1
 -12.55      1
 -8.45       1
 -11.45      1
 29.6        1
 31.7        1
 -7.5        1
 -13.2       1
 22.25       1
 4.4         1
 19.15       1
 29.85       1
 -29.95      1
 5.2         1
 9.4         1
 10.25       1
 38.1        1
 18.85       1
 33.15       1
 8.7         1
 31.6        1
 -3.5        1
 27.4        1
-12.85       1
 22.4        1
 27.2        1
 30.4        1
 -15.7       1
 18.0        1
-7.2         1
-13.4        1
-10.7        1
 -6.95       1
 -17.5       1
-13.3        1
-0.65        1
 -3.7        1
 27.5        1
 35.3        1
-32.7        1
 1.8         1
 3.95        1
 4.75        1
 31.3        1
 -10.5       1
 24.7        1
 -16.05      1
 17.05       1
 24.2        1
 -0.2        1
 32.75       1
 1.15        1
 16.8        1
 -26.2       1
 -7.3        1
 -15.75      1
 10.8        1
 -31.8       1
 37.4        1
 0.25        1
 15.25       1
 19.7        1
 4.5         1
 34.6        1
 -20.2       1
 12.5        1
 -23.75      1
 -0.95       1
 25.45       1
 -15.4       1
 -9.9        1
 35.3        1
 -6.6        1
 -12.2       1
 20.4        1
 0.55        1
 9.35        1
 34.9        1
 26.05       1
 -8.75       1
 3.2         1
 11.45       1
 32.15       1
 -24.8       1
 -2.4        1
 4.8         1
 -18.7       1
 -6.8        1
 3.5         1
 -8.15       1
 13.95       1
 -6.85       1
 27.85       1
 15.35       1
 1.7         1
 18.9        1
 22.95       1
 21.6        1
 43.25       1
 -10.2       1
 21.45       1
 7.55        1
 31.35       1
 9.8         1
 10.7        1
 27.95       1
 12.75       1
 7.2         1
 -12.8       1
 17.15       1
 -2.8        1
 17.95       1
 22.55       1
 27.2        1
 13.7        1
 11.7        1
 18.05       1
 18.2        1
 -4.3        1
 5.95        1
 -10.95      1
 -5.25       1
 11.8        1
 43.3        1
 35.15       1
 34.2        1
 26.6        1
 20.3        1
 26.35       1
 2.2         1
 7.7         1
 19.95       1
 -4.45       1
 33.2        1
 28.85       1
 18.7        1
 17.9        1
 27.45       1
 1.95        1
 -17.3       1
 27.8        1
 37.2        1
 -16.7       1
 32.85       1
 -10.3       1
 14.45       1
 -5.55       1
 12.85       1
 5.7         1
 -15.2       1
Name: count, dtype: int64

In [12]:
filtro5['fecha'].value_counts()

fecha
12/11/2021 19:00    1
12/01/2023 18:40    1
14/01/2023 15:29    1
14/01/2023 15:11    1
14/01/2023 13:40    1
14/01/2023 10:57    1
13/01/2023 20:35    1
13/01/2023 20:11    1
13/01/2023 18:42    1
13/01/2023 17:09    1
13/01/2023 14:24    1
13/01/2023 14:03    1
13/01/2023 13:39    1
13/01/2023 11:36    1
12/01/2023 19:09    1
12/01/2023 17:07    1
14/01/2023 17:11    1
12/01/2023 16:30    1
12/01/2023 13:30    1
12/01/2023 12:52    1
12/01/2023 11:08    1
11/01/2023 20:16    1
11/01/2023 18:31    1
11/01/2023 16:50    1
11/01/2023 12:35    1
10/01/2023 19:13    1
10/01/2023 18:42    1
10/01/2023 18:05    1
10/01/2023 13:18    1
09/01/2023 18:55    1
14/01/2023 15:43    1
14/01/2023 18:29    1
09/01/2023 17:32    1
16/01/2023 14:11    1
18/01/2023 11:39    1
18/01/2023 11:01    1
17/01/2023 19:58    1
17/01/2023 19:12    1
17/01/2023 18:03    1
17/01/2023 16:53    1
17/01/2023 15:22    1
17/01/2023 15:10    1
16/01/2023 18:24    1
16/01/2023 18:00    1
16/01/2023 17:24    1
16/01/2023 16:11    1
16/01/2023 15:41    1
16/01/2023 12:27    1
15/01/2023 10:28    1
16/01/2023 11:53    1
16/01/2023 11:26    1
16/01/2023 10:51    1
15/01/2023 18:16    1
15/01/2023 17:04    1
15/01/2023 16:35    1
15/01/2023 16:03    1
15/01/2023 15:20    1
15/01/2023 14:02    1
15/01/2023 13:53    1
15/01/2023 13:32    1
15/01/2023 12:07    1
15/01/2023 11:29    1
09/01/2023 18:08    1
09/01/2023 17:13    1
18/01/2023 14:21    1
05/01/2023 20:24    1
06/01/2023 14:43    1
06/01/2023 14:00    1
06/01/2023 12:15    1
06/01/2023 11:11    1
06/01/2023 10:38    1
06/01/2023 00:37    1
05/01/2023 22:52    1
05/01/2023 22:09    1
05/01/2023 21:48    1
05/01/2023 21:04    1
05/01/2023 20:53    1
05/01/2023 20:46    1
05/01/2023 20:41    1
05/01/2023 20:14    1
06/01/2023 16:04    1
05/01/2023 19:47    1
05/01/2023 19:36    1
05/01/2023 19:31    1
05/01/2023 19:08    1
05/01/2023 18:54    1
05/01/2023 18:50    1
05/01/2023 18:30    1
05/01/2023 18:04    1
05/01/2023 18:00    1
05/01/2023 17:50    1
05/01/2023 17:28    1
05/01/2023 17:14    1
05/01/2023 17:06    1
06/01/2023 15:28    1
06/01/2023 16:50    1
09/01/2023 16:02    1
08/01/2023 12:54    1
09/01/2023 15:36    1
09/01/2023 15:08    1
09/01/2023 14:23    1
09/01/2023 13:24    1
09/01/2023 13:11    1
09/01/2023 12:12    1
09/01/2023 10:19    1
08/01/2023 17:31    1
08/01/2023 16:24    1
08/01/2023 15:38    1
08/01/2023 15:13    1
08/01/2023 14:49    1
08/01/2023 13:36    1
08/01/2023 10:25    1
06/01/2023 17:42    1
07/01/2023 19:29    1
07/01/2023 18:56    1
07/01/2023 17:52    1
07/01/2023 16:30    1
07/01/2023 16:16    1
07/01/2023 14:38    1
07/01/2023 13:38    1
07/01/2023 12:36    1
07/01/2023 11:19    1
07/01/2023 10:33    1
06/01/2023 21:05    1
06/01/2023 18:15    1
06/01/2023 18:00    1
18/01/2023 14:08    1
18/01/2023 17:56    1
13/11/2021 16:10    1
28/01/2023 17:11    1
30/01/2023 16:40    1
30/01/2023 15:42    1
30/01/2023 12:50    1
29/01/2023 17:00    1
29/01/2023 16:20    1
29/01/2023 16:00    1
29/01/2023 15:32    1
29/01/2023 14:44    1
29/01/2023 14:37    1
29/01/2023 12:24    1
29/01/2023 11:20    1
29/01/2023 10:51    1
28/01/2023 18:10    1
28/01/2023 17:05    1
30/01/2023 19:19    1
28/01/2023 16:57    1
28/01/2023 15:57    1
28/01/2023 14:59    1
28/01/2023 14:37    1
28/01/2023 12:13    1
28/01/2023 10:57    1
28/01/2023 10:13    1
27/01/2023 18:08    1
27/01/2023 17:42    1
27/01/2023 17:14    1
27/01/2023 15:56    1
27/01/2023 14:24    1
27/01/2023 13:57    1
30/01/2023 17:48    1
30/01/2023 20:03    1
26/01/2023 21:33    1
02/02/2023 12:04    1
04/02/2023 13:27    1
04/02/2023 13:15    1
04/02/2023 12:33    1
03/02/2023 20:16    1
03/02/2023 19:15    1
03/02/2023 17:37    1
03/02/2023 16:46    1
03/02/2023 16:19    1
02/02/2023 19:40    1
02/02/2023 18:50    1
02/02/2023 16:25    1
02/02/2023 15:54    1
02/02/2023 12:50    1
01/02/2023 20:29    1
31/01/2023 12:38    1
01/02/2023 19:54    1
01/02/2023 19:04    1
01/02/2023 18:00    1
01/02/2023 16:38    1
01/02/2023 14:43    1
01/02/2023 14:19    1
01/02/2023 13:29    1
01/02/2023 12:33    1
01/02/2023 11:37    1
31/01/2023 17:39    1
31/01/2023 16:58    1
31/01/2023 16:38    1
31/01/2023 16:07    1
27/01/2023 12:07    1
26/01/2023 19:57    1
18/01/2023 18:24    1
20/01/2023 19:44    1
22/01/2023 11:28    1
22/01/2023 10:15    1
21/01/2023 18:43    1
21/01/2023 18:17    1
21/01/2023 18:07    1
21/01/2023 16:18    1
21/01/2023 15:45    1
21/01/2023 15:37    1
21/01/2023 14:48    1
21/01/2023 14:24    1
21/01/2023 14:13    1
21/01/2023 13:28    1
21/01/2023 11:05    1
20/01/2023 16:37    1
22/01/2023 13:25    1
20/01/2023 15:45    1
20/01/2023 13:05    1
20/01/2023 12:44    1
20/01/2023 11:16    1
19/01/2023 20:08    1
19/01/2023 18:27    1
19/01/2023 16:53    1
19/01/2023 16:16    1
19/01/2023 15:39    1
19/01/2023 14:50    1
19/01/2023 13:23    1
19/01/2023 12:02    1
18/01/2023 20:10    1
22/01/2023 12:45    1
22/01/2023 13:36    1
26/01/2023 18:28    1
25/01/2023 11:34    1
26/01/2023 17:49    1
26/01/2023 16:49    1
26/01/2023 16:39    1
26/01/2023 15:38    1
26/01/2023 14:35    1
26/01/2023 13:10    1
26/01/2023 12:36    1
26/01/2023 11:46    1
26/01/2023 10:40    1
25/01/2023 18:38    1
25/01/2023 16:17    1
25/01/2023 14:48    1
25/01/2023 11:53    1
24/01/2023 19:03    1
22/01/2023 13:59    1
24/01/2023 17:59    1
24/01/2023 16:44    1
24/01/2023 15:41    1
24/01/2023 15:07    1
24/01/2023 13:51    1
24/01/2023 11:49    1
23/01/2023 19:12    1
23/01/2023 17:23    1
23/01/2023 14:25    1
23/01/2023 13:23    1
23/01/2023 11:37    1
22/01/2023 17:04    1
22/01/2023 14:51    1
05/01/2023 16:36    1
05/01/2023 16:30    1
05/01/2023 16:25    1
22/12/2022 17:06    1
23/12/2022 16:26    1
23/12/2022 16:07    1
23/12/2022 15:49    1
23/12/2022 15:09    1
23/12/2022 14:35    1
23/12/2022 14:19    1
23/12/2022 13:58    1
23/12/2022 12:27    1
23/12/2022 12:14    1
23/12/2022 11:24    1
23/12/2022 10:51    1
22/12/2022 18:41    1
22/12/2022 17:50    1
22/12/2022 16:21    1
23/12/2022 17:31    1
22/12/2022 16:13    1
22/12/2022 15:27    1
22/12/2022 14:49    1
22/12/2022 14:22    1
22/12/2022 13:25    1
22/12/2022 13:06    1
22/12/2022 12:23    1
22/12/2022 10:44    1
21/12/2022 20:36    1
21/12/2022 19:51    1
21/12/2022 18:55    1
21/12/2022 18:38    1
21/12/2022 18:18    1
23/12/2022 16:54    1
23/12/2022 17:37    1
21/12/2022 17:29    1
24/12/2022 18:09    1
26/12/2022 10:04    1
25/12/2022 17:36    1
25/12/2022 16:42    1
25/12/2022 15:40    1
25/12/2022 15:02    1
25/12/2022 14:39    1
25/12/2022 14:11    1
25/12/2022 12:43    1
24/12/2022 19:25    1
24/12/2022 19:06    1
24/12/2022 18:47    1
24/12/2022 18:34    1
24/12/2022 18:25    1
24/12/2022 17:39    1
23/12/2022 18:20    1
24/12/2022 17:27    1
24/12/2022 16:52    1
24/12/2022 16:48    1
24/12/2022 16:24    1
24/12/2022 16:14    1
24/12/2022 15:38    1
24/12/2022 14:28    1
24/12/2022 14:11    1
24/12/2022 13:28    1
24/12/2022 12:59    1
24/12/2022 12:48    1
24/12/2022 09:25    1
23/12/2022 18:41    1
21/12/2022 17:50    1
21/12/2022 17:07    1
05/01/2023 16:15    1
17/12/2022 13:47    1
18/12/2022 12:58    1
17/12/2022 20:08    1
17/12/2022 19:57    1
17/12/2022 18:57    1
17/12/2022 18:35    1
17/12/2022 17:38    1
17/12/2022 17:02    1
17/12/2022 16:43    1
17/12/2022 15:54    1
17/12/2022 15:11    1
17/12/2022 14:48    1
17/12/2022 14:20    1
17/12/2022 14:01    1
17/12/2022 13:17    1
18/12/2022 13:40    1
17/12/2022 12:20    1
17/12/2022 10:03    1
16/12/2022 18:58    1
16/12/2022 17:39    1
16/12/2022 15:50    1
16/12/2022 15:21    1
16/12/2022 15:05    1
16/12/2022 14:21    1
16/12/2022 14:07    1
16/12/2022 12:55    1
16/12/2022 12:44    1
16/12/2022 11:15    1
15/12/2022 18:15    1
18/12/2022 13:19    1
18/12/2022 14:59    1
21/12/2022 17:01    1
19/12/2022 20:21    1
21/12/2022 16:50    1
21/12/2022 16:24    1
21/12/2022 15:32    1
21/12/2022 13:46    1
21/12/2022 13:40    1
21/12/2022 12:03    1
21/12/2022 11:40    1
21/12/2022 10:49    1
20/12/2022 18:44    1
20/12/2022 18:13    1
20/12/2022 17:52    1
20/12/2022 17:15    1
20/12/2022 13:58    1
19/12/2022 19:54    1
18/12/2022 15:36    1
19/12/2022 19:38    1
19/12/2022 19:07    1
19/12/2022 17:11    1
19/12/2022 16:19    1
19/12/2022 15:58    1
19/12/2022 15:23    1
19/12/2022 15:01    1
19/12/2022 14:56    1
19/12/2022 13:51    1
19/12/2022 13:09    1
19/12/2022 12:31    1
18/12/2022 17:19    1
18/12/2022 16:46    1
26/12/2022 11:12    1
26/12/2022 12:25    1
26/12/2022 12:45    1
02/01/2023 19:05    1
03/01/2023 20:39    1
03/01/2023 18:06    1
03/01/2023 16:59    1
03/01/2023 16:47    1
03/01/2023 16:24    1
03/01/2023 16:04    1
03/01/2023 14:32    1
03/01/2023 14:13    1
03/01/2023 12:38    1
03/01/2023 12:17    1
03/01/2023 11:16    1
03/01/2023 10:16    1
02/01/2023 21:33    1
02/01/2023 18:56    1
04/01/2023 12:41    1
02/01/2023 17:29    1
02/01/2023 16:56    1
02/01/2023 16:43    1
02/01/2023 16:24    1
02/01/2023 16:11    1
02/01/2023 15:55    1
02/01/2023 15:17    1
02/01/2023 13:35    1
02/01/2023 13:21    1
31/12/2022 18:25    1
31/12/2022 17:25    1
31/12/2022 16:27    1
31/12/2022 16:10    1
04/01/2023 10:59    1
04/01/2023 13:08    1
26/12/2022 12:58    1
05/01/2023 10:36    1
05/01/2023 16:00    1
05/01/2023 15:53    1
05/01/2023 15:18    1
05/01/2023 14:56    1
05/01/2023 14:06    1
05/01/2023 13:33    1
05/01/2023 13:09    1
05/01/2023 12:57    1
05/01/2023 12:04    1
05/01/2023 11:50    1
05/01/2023 11:39    1
05/01/2023 11:24    1
05/01/2023 11:19    1
04/01/2023 20:56    1
04/01/2023 13:34    1
04/01/2023 19:51    1
04/01/2023 19:11    1
04/01/2023 18:35    1
04/01/2023 18:23    1
04/01/2023 17:25    1
04/01/2023 17:04    1
04/01/2023 16:51    1
04/01/2023 16:37    1
04/01/2023 16:34    1
04/01/2023 15:59    1
04/01/2023 15:27    1
04/01/2023 14:36    1
04/01/2023 14:05    1
31/12/2022 15:53    1
31/12/2022 15:43    1
31/12/2022 12:17    1
27/12/2022 15:12    1
28/12/2022 14:03    1
28/12/2022 13:11    1
28/12/2022 12:41    1
28/12/2022 12:03    1
28/12/2022 11:39    1
28/12/2022 10:46    1
27/12/2022 19:28    1
27/12/2022 19:05    1
27/12/2022 19:00    1
27/12/2022 17:35    1
27/12/2022 16:57    1
27/12/2022 16:20    1
27/12/2022 15:52    1
27/12/2022 14:18    1
31/12/2022 11:30    1
27/12/2022 13:45    1
27/12/2022 12:59    1
26/12/2022 19:47    1
26/12/2022 18:10    1
26/12/2022 18:01    1
26/12/2022 17:38    1
26/12/2022 17:28    1
26/12/2022 16:12    1
26/12/2022 15:52    1
26/12/2022 15:40    1
26/12/2022 14:43    1
26/12/2022 14:06    1
26/12/2022 13:50    1
28/12/2022 14:13    1
28/12/2022 14:40    1
28/12/2022 15:25    1
28/12/2022 15:55    1
31/12/2022 11:06    1
31/12/2022 10:26    1
31/12/2022 10:01    1
30/12/2022 20:46    1
30/12/2022 20:12    1
30/12/2022 18:43    1
30/12/2022 18:06    1
30/12/2022 17:29    1
30/12/2022 17:10    1
30/12/2022 15:13    1
30/12/2022 14:43    1
30/12/2022 11:53    1
30/12/2022 09:49    1
29/12/2022 19:44    1
29/12/2022 18:33    1
29/12/2022 18:06    1
29/12/2022 16:48    1
29/12/2022 14:55    1
29/12/2022 13:22    1
29/12/2022 12:18    1
29/12/2022 11:56    1
28/12/2022 19:57    1
28/12/2022 19:03    1
28/12/2022 18:44    1
28/12/2022 18:23    1
28/12/2022 17:47    1
28/12/2022 16:33    1
04/02/2023 13:55    1
04/02/2023 14:37    1
04/02/2023 15:45    1
24/03/2023 12:42    1
26/03/2023 10:50    1
26/03/2023 10:29    1
26/03/2023 10:03    1
26/03/2023 09:40    1
25/03/2023 14:05    1
25/03/2023 10:43    1
24/03/2023 18:33    1
24/03/2023 17:25    1
24/03/2023 16:50    1
24/03/2023 16:37    1
24/03/2023 15:39    1
24/03/2023 15:00    1
24/03/2023 13:23    1
24/03/2023 12:12    1
26/03/2023 12:51    1
24/03/2023 11:19    1
23/03/2023 20:03    1
23/03/2023 18:37    1
23/03/2023 18:09    1
23/03/2023 17:30    1
23/03/2023 14:22    1
23/03/2023 13:41    1
23/03/2023 12:40    1
22/03/2023 20:14    1
22/03/2023 17:20    1
22/03/2023 16:33    1
22/03/2023 16:13    1
22/03/2023 15:29    1
26/03/2023 11:22    1
26/03/2023 13:20    1
22/03/2023 13:12    1
28/03/2023 19:54    1
31/03/2023 18:32    1
31/03/2023 17:30    1
31/03/2023 17:08    1
31/03/2023 14:55    1
31/03/2023 11:45    1
30/03/2023 19:43    1
30/03/2023 19:15    1
30/03/2023 17:44    1
30/03/2023 15:41    1
30/03/2023 12:07    1
29/03/2023 17:15    1
29/03/2023 15:23    1
29/03/2023 14:09    1
28/03/2023 19:07    1
26/03/2023 14:26    1
28/03/2023 18:28    1
28/03/2023 16:19    1
28/03/2023 14:23    1
28/03/2023 11:19    1
27/03/2023 21:26    1
27/03/2023 17:45    1
27/03/2023 14:07    1
27/03/2023 13:50    1
27/03/2023 13:03    1
27/03/2023 12:39    1
27/03/2023 10:24    1
26/03/2023 17:29    1
26/03/2023 15:11    1
22/03/2023 14:09    1
22/03/2023 12:16    1
13/03/2023 12:59    1
15/03/2023 12:47    1
18/03/2023 14:06    1
18/03/2023 13:22    1
17/03/2023 18:24    1
17/03/2023 17:56    1
17/03/2023 15:51    1
16/03/2023 18:21    1
16/03/2023 17:22    1
16/03/2023 09:50    1
15/03/2023 20:43    1
15/03/2023 19:56    1
15/03/2023 18:59    1
15/03/2023 18:05    1
15/03/2023 16:14    1
15/03/2023 12:22    1
18/03/2023 16:02    1
14/03/2023 20:21    1
14/03/2023 17:48    1
14/03/2023 16:27    1
14/03/2023 14:21    1
14/03/2023 13:36    1
14/03/2023 13:25    1
14/03/2023 11:41    1
13/03/2023 20:09    1
13/03/2023 19:42    1
13/03/2023 18:07    1
13/03/2023 17:13    1
13/03/2023 16:40    1
13/03/2023 16:13    1
18/03/2023 15:34    1
18/03/2023 16:25    1
22/03/2023 11:51    1
20/03/2023 13:54    1
22/03/2023 11:06    1
22/03/2023 09:59    1
21/03/2023 17:41    1
21/03/2023 14:38    1
21/03/2023 14:09    1
21/03/2023 13:52    1
21/03/2023 13:08    1
21/03/2023 12:21    1
20/03/2023 17:59    1
20/03/2023 17:13    1
20/03/2023 15:32    1
20/03/2023 14:18    1
20/03/2023 14:06    1
20/03/2023 13:19    1
18/03/2023 17:36    1
19/03/2023 18:04    1
19/03/2023 17:14    1
19/03/2023 16:51    1
19/03/2023 16:22    1
19/03/2023 14:53    1
19/03/2023 14:46    1
19/03/2023 14:36    1
19/03/2023 14:22    1
19/03/2023 13:51    1
19/03/2023 13:34    1
18/03/2023 18:59    1
18/03/2023 18:17    1
18/03/2023 17:59    1
01/04/2023 12:11    1
01/04/2023 12:28    1
01/04/2023 14:08    1
12/04/2023 13:00    1
14/04/2023 11:33    1
14/04/2023 11:07    1
13/04/2023 18:22    1
13/04/2023 17:33    1
13/04/2023 16:48    1
13/04/2023 13:10    1
12/04/2023 19:50    1
12/04/2023 18:37    1
12/04/2023 17:29    1
12/04/2023 16:29    1
12/04/2023 15:57    1
12/04/2023 14:29    1
12/04/2023 14:10    1
12/04/2023 11:32    1
14/04/2023 18:21    1
11/04/2023 19:31    1
11/04/2023 16:13    1
11/04/2023 15:05    1
11/04/2023 14:32    1
11/04/2023 13:51    1
11/04/2023 12:25    1
11/04/2023 11:29    1
10/04/2023 18:27    1
10/04/2023 17:55    1
10/04/2023 17:38    1
10/04/2023 17:05    1
10/04/2023 16:43    1
10/04/2023 15:44    1
14/04/2023 17:29    1
15/04/2023 10:16    1
01/04/2023 14:25    1
17/04/2023 11:28    1
18/04/2023 14:12    1
18/04/2023 13:13    1
18/04/2023 12:39    1
18/04/2023 11:53    1
18/04/2023 08:54    1
17/04/2023 19:25    1
17/04/2023 18:41    1
17/04/2023 18:03    1
17/04/2023 17:16    1
17/04/2023 16:45    1
17/04/2023 13:20    1
17/04/2023 12:27    1
17/04/2023 11:52    1
17/04/2023 10:30    1
15/04/2023 11:48    1
17/04/2023 09:32    1
16/04/2023 15:31    1
16/04/2023 12:58    1
16/04/2023 12:23    1
16/04/2023 11:42    1
15/04/2023 19:21    1
15/04/2023 18:40    1
15/04/2023 18:34    1
15/04/2023 15:24    1
15/04/2023 15:05    1
15/04/2023 14:10    1
15/04/2023 13:43    1
15/04/2023 13:31    1
10/04/2023 15:15    1
10/04/2023 13:22    1
10/04/2023 12:43    1
03/04/2023 19:08    1
05/04/2023 20:45    1
05/04/2023 19:26    1
05/04/2023 18:04    1
05/04/2023 13:56    1
05/04/2023 12:07    1
04/04/2023 19:17    1
04/04/2023 18:28    1
04/04/2023 17:49    1
04/04/2023 15:15    1
04/04/2023 14:40    1
04/04/2023 13:10    1
03/04/2023 21:13    1
03/04/2023 20:08    1
03/04/2023 17:27    1
10/04/2023 10:17    1
03/04/2023 15:09    1
03/04/2023 14:07    1
03/04/2023 13:50    1
02/04/2023 16:05    1
02/04/2023 12:24    1
02/04/2023 12:05    1
02/04/2023 11:48    1
01/04/2023 19:46    1
01/04/2023 19:30    1
01/04/2023 19:13    1
01/04/2023 18:27    1
01/04/2023 16:47    1
01/04/2023 14:56    1
06/04/2023 10:52    1
06/04/2023 13:32    1
06/04/2023 14:19    1
06/04/2023 14:41    1
09/04/2023 18:40    1
09/04/2023 17:51    1
09/04/2023 16:04    1
09/04/2023 13:50    1
09/04/2023 10:46    1
09/04/2023 09:52    1
08/04/2023 18:52    1
08/04/2023 18:21    1
08/04/2023 17:43    1
08/04/2023 16:26    1
08/04/2023 15:59    1
08/04/2023 15:22    1
08/04/2023 13:48    1
08/04/2023 13:19    1
08/04/2023 12:43    1
08/04/2023 12:12    1
07/04/2023 18:21    1
07/04/2023 16:38    1
07/04/2023 15:24    1
07/04/2023 13:56    1
07/04/2023 13:29    1
07/04/2023 12:29    1
07/04/2023 11:34    1
06/04/2023 18:35    1
06/04/2023 17:56    1
06/04/2023 16:51    1
06/04/2023 16:42    1
13/03/2023 15:01    1
13/03/2023 11:50    1
04/02/2023 16:56    1
16/02/2023 16:15    1
18/02/2023 11:02    1
17/02/2023 21:06    1
17/02/2023 20:31    1
17/02/2023 17:31    1
17/02/2023 16:38    1
17/02/2023 16:04    1
17/02/2023 15:49    1
17/02/2023 14:37    1
17/02/2023 13:49    1
17/02/2023 10:45    1
17/02/2023 09:22    1
16/02/2023 19:07    1
16/02/2023 17:53    1
16/02/2023 14:51    1
18/02/2023 14:05    1
16/02/2023 12:03    1
15/02/2023 19:08    1
15/02/2023 18:58    1
15/02/2023 17:04    1
15/02/2023 15:00    1
14/02/2023 21:02    1
14/02/2023 20:01    1
14/02/2023 19:40    1
14/02/2023 17:25    1
14/02/2023 16:52    1
14/02/2023 16:09    1
14/02/2023 15:09    1
14/02/2023 13:01    1
18/02/2023 13:54    1
18/02/2023 15:46    1
14/02/2023 11:46    1
20/02/2023 15:21    1
23/02/2023 11:46    1
22/02/2023 19:31    1
22/02/2023 18:39    1
22/02/2023 16:27    1
22/02/2023 14:31    1
21/02/2023 17:04    1
21/02/2023 16:13    1
21/02/2023 12:56    1
21/02/2023 12:39    1
21/02/2023 11:36    1
20/02/2023 18:59    1
20/02/2023 17:54    1
20/02/2023 17:23    1
20/02/2023 14:58    1
18/02/2023 16:05    1
20/02/2023 13:55    1
20/02/2023 10:54    1
19/02/2023 16:52    1
19/02/2023 16:30    1
19/02/2023 13:21    1
19/02/2023 13:13    1
19/02/2023 13:00    1
19/02/2023 12:17    1
18/02/2023 20:23    1
18/02/2023 19:05    1
18/02/2023 18:15    1
18/02/2023 17:09    1
18/02/2023 16:17    1
14/02/2023 12:44    1
13/02/2023 20:17    1
13/03/2023 10:49    1
06/02/2023 16:03    1
08/02/2023 18:06    1
08/02/2023 17:43    1
08/02/2023 11:15    1
07/02/2023 20:59    1
07/02/2023 19:36    1
07/02/2023 19:04    1
07/02/2023 17:53    1
07/02/2023 16:26    1
07/02/2023 15:39    1
07/02/2023 11:16    1
07/02/2023 09:38    1
06/02/2023 17:39    1
06/02/2023 16:53    1
06/02/2023 15:39    1
08/02/2023 20:26    1
06/02/2023 14:18    1
06/02/2023 13:35    1
06/02/2023 11:11    1
05/02/2023 16:59    1
05/02/2023 16:24    1
05/02/2023 15:54    1
05/02/2023 14:56    1
05/02/2023 14:01    1
05/02/2023 12:18    1
05/02/2023 12:04    1
04/02/2023 18:53    1
04/02/2023 17:17    1
04/02/2023 17:09    1
08/02/2023 19:46    1
09/02/2023 14:39    1
13/02/2023 19:24    1
11/02/2023 16:29    1
13/02/2023 18:11    1
13/02/2023 17:50    1
13/02/2023 17:11    1
13/02/2023 16:24    1
13/02/2023 14:58    1
13/02/2023 10:45    1
12/02/2023 17:26    1
12/02/2023 17:05    1
12/02/2023 15:38    1
12/02/2023 15:23    1
12/02/2023 13:33    1
12/02/2023 11:59    1
11/02/2023 17:08    1
11/02/2023 16:16    1
09/02/2023 16:57    1
11/02/2023 15:57    1
11/02/2023 15:31    1
11/02/2023 14:55    1
10/02/2023 19:26    1
10/02/2023 18:29    1
10/02/2023 17:58    1
10/02/2023 16:13    1
10/02/2023 15:53    1
10/02/2023 14:17    1
10/02/2023 12:57    1
09/02/2023 19:10    1
09/02/2023 18:48    1
09/02/2023 17:37    1
23/02/2023 12:50    1
23/02/2023 20:32    1
24/02/2023 12:25    1
07/03/2023 15:42    1
09/03/2023 11:13    1
09/03/2023 09:31    1
08/03/2023 19:24    1
08/03/2023 17:05    1
08/03/2023 16:22    1
08/03/2023 14:09    1
08/03/2023 13:38    1
08/03/2023 11:24    1
08/03/2023 10:24    1
07/03/2023 20:23    1
07/03/2023 18:40    1
07/03/2023 17:35    1

In [13]:
###todos los registros cuya fecha sea posterior al 15/11/2021
filtro6 = filtro5[filtro5['fecha'] > '2021-11-15']

In [18]:
filtro5

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
28,74DZR6G2,23/11/2021 15:17,MOTOROLA,LTE XT2097-12 E7I POWER Naranja,26S,3299.00,990.0,0.0,160,2309.00,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
32,4VK0M9IK,26/11/2021 11:07,MOTOROLA,G10 B,39S,4299.00,1290.0,0.0,166,3009.00,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
36,HKHZDPMU,28/11/2021 12:35,NOKIA,1.4 2/32 AZUL B,26S,2599.00,650.0,0.0,135,1949.00,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
40,RYCSU33I,29/11/2021 16:52,MOTOROLA,MOTO G60 6+128 GB GRIS B,13S,7399.00,1850.0,0.0,640,5549.00,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0
44,VNOHNLYD,30/11/2021 17:21,MOTOROLA,E7I POWER 2+32 GB ROJO B,52S,2999.00,750.0,0.0,112,2249.00,...,24/05/2022 00:00,Mora,0.0,0,0.00,0.0,0.0,NaN,NaN,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21272,FQ96BJJR,31/03/2023 11:45,MOTOROLA,4G XT2239-17 E22I Gris Kit,39S,3508.83,628.0,0.0,159,2880.83,...,21/04/2023 00:00,Corriente,12.0,-8.1,-1.09,0.0,0.0,"D2,E0,G1,J0",3,93537
21292,J1QFES9J,31/03/2023 14:55,MOTOROLA,MOTO G41 4+128 GB NEGRO B,39S,5128.86,1267.0,0.0,213,3861.86,...,14/04/2023 00:00,Atraso,10.0,13.4,2.70,0.0,0.0,"K0,F7,D8,D7",3,93534
21304,2A8UXV52,31/03/2023 17:08,NOKIA,C20 2+32GB AZUL B,26S,2455.83,583.0,0.0,130,1872.83,...,22/04/2023 00:00,Corriente,10.0,2.6,3.75,0.0,0.0,"F7,E4,D7,J0",3,95000
21308,3XCGH06H,31/03/2023 17:30,ZTE,BLADE A52 LITE 2+32GB GRIS B,26S,2572.83,696.0,0.0,130,1876.83,...,21/04/2023 00:00,Corriente,10.0,5.0,6.04,0.0,0.0,"F7,E4,D7,J0",3,72380
21316,POR0M1CD,31/03/2023 18:32,NOKIA,C20 2+32GB AZUL B,13S,2455.83,513.0,0.0,224,1942.83,...,14/04/2023 00:00,Atraso,14.0,17.35,-1.10,0.0,0.0,C2,3,73660

In [14]:
####convertir a csv
filtro6.to_csv('evaluacionpt1buena.csv', index=False)